name: Validate

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_run:
    workflows:
      - Update web header
    types:
      - completed
    branches:
      - master

jobs:
  build-esp32:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Checkout test firmware repo
        uses: actions/checkout@master
        with:
          repository: PavelProjects/SmartThingLibTest
          path: ./SmartThingLibTest
      - run: mv ./src ./smartthing
      - run: mkdir ./SmartThingLibTest/lib
      - run: mv ./smartthing ./SmartThingLibTest/lib/smartthing
      - name: Build PlatformIO Project
        run: pio run -d ./SmartThingLibTest -e esp32
  build-esp8266:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Checkout test firmware repo
        uses: actions/checkout@master
        with:
          repository: PavelProjects/SmartThingLibTest
          path: ./SmartThingLibTest
      - run: mv ./src ./smartthing
      - run: mkdir ./SmartThingLibTest/lib
      - run: mv ./smartthing ./SmartThingLibTest/lib/smartthing
      - name: Build PlatformIO Project
        run: pio run -d ./SmartThingLibTest -e esp8266
