name: Update web header

on:
  repository_dispatch:
    types: [ui_update]

env:
  COMMIT_MESSAGE: ${{ github.event.client_payload.message }}

jobs:
  update-web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout lib repository
        uses: actions/checkout@v4
        with:
          path: ./lib
          ref: develop
      - run: export LIB_DIR="$(pwd)/lib"
      - name: Checkout web repository
        uses: actions/checkout@master
        with:
          repository: PavelProjects/SmartThingLibWeb
          path: ./web
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update web header
        working-directory: ./web
        run: |
          npm ci
          npm run build-header
      - name: Copy header file
        run: cp ./web/dist/WebPageAssets.h ./lib//src/net/rest/WebPageAssets.h
      - name: Commit and push changes
        working-directory: ./lib
        run: |
          git config --global user.name 'web-updater[bot]'
          git config --global user.email '<>'
          git commit -am "Auto web assets update: $COMMIT_MESSAGE"
          git push origin develop
