name: Update web header

on:
  repository_dispatch:
    types: [ui_update]

env:
  COMMIT_MESSAGE: ${{ github.event.client_payload.message }}

jobs:
  update-web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - run: echo $COMMIT_MESSAGE
      - name: Checkout lib repository
        uses: actions/checkout@v4
        with:
          path: ./lib
      - run: |
          export LIB_DIR="$(pwd)/lib"
          echo $LIB_DIR
          ls -l
      - name: Checkout web repository
        uses: actions/checkout@master
        with:
          repository: PavelProjects/SmartThingLibWeb
          path: ./web
      - run: cd ./web
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Update header header
        run: npm run deploy-header --dest $LIB_DIR